### ISSUE TITLE
Add spectator@1 error

### ISSUE THREAD

**Issue by julywind168** [JonasGruenwald/spectator#1]
error: Dependency resolution failed

An error occurred while determining what dependency packages and
versions should be downloaded.
The error from the version resolver library was:

Unable to find compatible versions for the version constraints in your
gleam.toml. The conflicting packages are:

- gleam_json
- ...

maybe gleam_json should update to 2.0.0

**Comment by JonasGruenwald** [comment]
Hello! 
I don't think increasing the version range for gleam_json in this package will change anything for you here, since spectator depends on lustre, which pins it to v1 anyway https://github.com/lustre-labs/lustre/blob/main/gleam.toml#L37 
What is the `...` ? Did you remove which other packages are conflicting, or was there nothing else?

**Comment by JonasGruenwald** [comment]
Actually funny that you mention it, just noticed I'm not actually using gleam_json anywhere, so I removed it from the direct dependencies entirely.

**Comment by julywind168** [comment]
I change my project gleam_json = "~> 1.0", now add spectator success.
